# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: MZD-Commerce
  title: 메가존 커머스 
spec:
  owner: mzd-department-dxlabs
