apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: argocd
  title: ArgoCD
  description: Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. We use ArgoCD for the deployment of this showcase.
  links:
    - url: https://argocd.aimegazone.com/
      title: Instance of ArgoCD
      icon: web
    - url: https://argocd.readthedocs.io/en/stable/
      title: Documentation
      icon: web
      
spec:
  type: identity-provider
  lifecycle: production
  owner: mzd-team-platform-architecture
  system: megazone-idp
