apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: mzd
  description: "메가존 디지털"
  links:
    - url: http://mz.co.kr/
      title: Website
spec:
  type: 회사
  profile:
    displayName: 메가존 디지털
    email: mz@mz.co.kr
    picture: https://shareditassets.s3.ap-northeast-2.amazonaws.com/production/uploads/business/profile_photo/2476/low_%E1%84%86%E1%85%A6%E1%84%80%E1%85%A1%E1%84%8C%E1%85%A9%E1%86%AB_%E1%84%83%E1%85%B5%E1%84%8C%E1%85%B5%E1%84%90%E1%85%A5%E1%86%AF.png
  children:
    - mzd-department-dxlabs