apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: domain-iiac
  title: IIAC
  description: 인천공항공사
  links:
    - url: http://example.com/domain/audio/
      title: Domain Readme
    - url: http://example.com/domains/audio/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: mzd-department-dxlabs
