apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: location-organizations-mzd
  description: MZD 그룹
spec:
  targets:
    - https://github.com/mzd-lab/backstage-catalog/blob/main/organizations/mzd/groups/company.yaml
